#!/bin/bash

sbatch small_cnn_train.sh --use_gpu --train_path  --val_path  --output_path  --test_path  --name small_cnn --type small_cnn --batch_size 20 --learning_rate 0.001 --epoch_count 20 --weight_decay 0 --small_cnn_kernel_size 3 --small_cnn_first_output_channels 2 --small_cnn_growth_rate 2
sbatch small_cnn_train.sh --use_gpu --train_path  --val_path  --output_path  --test_path  --name small_cnn --type small_cnn --batch_size 20 --learning_rate 0.001 --epoch_count 20 --weight_decay 0 --small_cnn_kernel_size 3 --small_cnn_first_output_channels 2 --small_cnn_growth_rate 3
sbatch small_cnn_train.sh --use_gpu --train_path  --val_path  --output_path  --test_path  --name small_cnn --type small_cnn --batch_size 20 --learning_rate 0.001 --epoch_count 20 --weight_decay 0 --small_cnn_kernel_size 3 --small_cnn_first_output_channels 4 --small_cnn_growth_rate 2
sbatch small_cnn_train.sh --use_gpu --train_path  --val_path  --output_path  --test_path  --name small_cnn --type small_cnn --batch_size 20 --learning_rate 0.001 --epoch_count 20 --weight_decay 0 --small_cnn_kernel_size 3 --small_cnn_first_output_channels 4 --small_cnn_growth_rate 3
sbatch small_cnn_train.sh --use_gpu --train_path  --val_path  --output_path  --test_path  --name small_cnn --type small_cnn --batch_size 20 --learning_rate 0.001 --epoch_count 20 --weight_decay 0 --small_cnn_kernel_size 3 --small_cnn_first_output_channels 8 --small_cnn_growth_rate 2
sbatch small_cnn_train.sh --use_gpu --train_path  --val_path  --output_path  --test_path  --name small_cnn --type small_cnn --batch_size 20 --learning_rate 0.001 --epoch_count 20 --weight_decay 0 --small_cnn_kernel_size 3 --small_cnn_first_output_channels 8 --small_cnn_growth_rate 3
sbatch small_cnn_train.sh --use_gpu --train_path  --val_path  --output_path  --test_path  --name small_cnn --type small_cnn --batch_size 20 --learning_rate 0.001 --epoch_count 20 --weight_decay 0 --small_cnn_kernel_size 3 --small_cnn_first_output_channels 16 --small_cnn_growth_rate 2
sbatch small_cnn_train.sh --use_gpu --train_path  --val_path  --output_path  --test_path  --name small_cnn --type small_cnn --batch_size 20 --learning_rate 0.001 --epoch_count 20 --weight_decay 0 --small_cnn_kernel_size 3 --small_cnn_first_output_channels 16 --small_cnn_growth_rate 3
sbatch small_cnn_train.sh --use_gpu --train_path  --val_path  --output_path  --test_path  --name small_cnn --type small_cnn --batch_size 20--data_augmentation --learning_rate 0.001 --epoch_count 20 --weight_decay 0 --small_cnn_kernel_size 3 --small_cnn_first_output_channels 2 --small_cnn_growth_rate 2
sbatch small_cnn_train.sh --use_gpu --train_path  --val_path  --output_path  --test_path  --name small_cnn --type small_cnn --batch_size 20--data_augmentation --learning_rate 0.001 --epoch_count 20 --weight_decay 0 --small_cnn_kernel_size 3 --small_cnn_first_output_channels 2 --small_cnn_growth_rate 3
sbatch small_cnn_train.sh --use_gpu --train_path  --val_path  --output_path  --test_path  --name small_cnn --type small_cnn --batch_size 20--data_augmentation --learning_rate 0.001 --epoch_count 20 --weight_decay 0 --small_cnn_kernel_size 3 --small_cnn_first_output_channels 4 --small_cnn_growth_rate 2
sbatch small_cnn_train.sh --use_gpu --train_path  --val_path  --output_path  --test_path  --name small_cnn --type small_cnn --batch_size 20--data_augmentation --learning_rate 0.001 --epoch_count 20 --weight_decay 0 --small_cnn_kernel_size 3 --small_cnn_first_output_channels 4 --small_cnn_growth_rate 3
sbatch small_cnn_train.sh --use_gpu --train_path  --val_path  --output_path  --test_path  --name small_cnn --type small_cnn --batch_size 20--data_augmentation --learning_rate 0.001 --epoch_count 20 --weight_decay 0 --small_cnn_kernel_size 3 --small_cnn_first_output_channels 8 --small_cnn_growth_rate 2
sbatch small_cnn_train.sh --use_gpu --train_path  --val_path  --output_path  --test_path  --name small_cnn --type small_cnn --batch_size 20--data_augmentation --learning_rate 0.001 --epoch_count 20 --weight_decay 0 --small_cnn_kernel_size 3 --small_cnn_first_output_channels 8 --small_cnn_growth_rate 3
sbatch small_cnn_train.sh --use_gpu --train_path  --val_path  --output_path  --test_path  --name small_cnn --type small_cnn --batch_size 20--data_augmentation --learning_rate 0.001 --epoch_count 20 --weight_decay 0 --small_cnn_kernel_size 3 --small_cnn_first_output_channels 16 --small_cnn_growth_rate 2
sbatch small_cnn_train.sh --use_gpu --train_path  --val_path  --output_path  --test_path  --name small_cnn --type small_cnn --batch_size 20--data_augmentation --learning_rate 0.001 --epoch_count 20 --weight_decay 0 --small_cnn_kernel_size 3 --small_cnn_first_output_channels 16 --small_cnn_growth_rate 3
