#!/bin/bash

sbatch train_corridor.sh --use_gpu --output_path ~/CuriousNetwork/nn/cnn_autoencoder/2/--name n --type cnn_autoencoder --batch_size 20 --learning_rate 0.001 --epoch_count 20 --weight_decay 0 --cnn_autoencoder_starting_feature_map 2 --cnn_autoencoder_growth_factor 2 --cnn_autoencoder_kernel_size 3
sbatch train_corridor.sh --use_gpu --output_path ~/CuriousNetwork/nn/cnn_autoencoder/2/--name n --type cnn_autoencoder --batch_size 20 --learning_rate 0.001 --epoch_count 20 --weight_decay 0 --cnn_autoencoder_starting_feature_map 2 --cnn_autoencoder_growth_factor 3 --cnn_autoencoder_kernel_size 3
sbatch train_corridor.sh --use_gpu --output_path ~/CuriousNetwork/nn/cnn_autoencoder/4/--name n --type cnn_autoencoder --batch_size 20 --learning_rate 0.001 --epoch_count 20 --weight_decay 0 --cnn_autoencoder_starting_feature_map 4 --cnn_autoencoder_growth_factor 2 --cnn_autoencoder_kernel_size 3
sbatch train_corridor.sh --use_gpu --output_path ~/CuriousNetwork/nn/cnn_autoencoder/4/--name n --type cnn_autoencoder --batch_size 20 --learning_rate 0.001 --epoch_count 20 --weight_decay 0 --cnn_autoencoder_starting_feature_map 4 --cnn_autoencoder_growth_factor 3 --cnn_autoencoder_kernel_size 3
sbatch train_corridor.sh --use_gpu --output_path ~/CuriousNetwork/nn/cnn_autoencoder/8/--name n --type cnn_autoencoder --batch_size 20 --learning_rate 0.001 --epoch_count 20 --weight_decay 0 --cnn_autoencoder_starting_feature_map 8 --cnn_autoencoder_growth_factor 2 --cnn_autoencoder_kernel_size 3
sbatch train_corridor.sh --use_gpu --output_path ~/CuriousNetwork/nn/cnn_autoencoder/8/--name n --type cnn_autoencoder --batch_size 20 --learning_rate 0.001 --epoch_count 20 --weight_decay 0 --cnn_autoencoder_starting_feature_map 8 --cnn_autoencoder_growth_factor 3 --cnn_autoencoder_kernel_size 3
sbatch train_corridor.sh --use_gpu --output_path ~/CuriousNetwork/nn/cnn_autoencoder/2/--name n --type cnn_autoencoder --batch_size 20--data_augmentation --learning_rate 0.001 --epoch_count 20 --weight_decay 0 --cnn_autoencoder_starting_feature_map 2 --cnn_autoencoder_growth_factor 2 --cnn_autoencoder_kernel_size 3
sbatch train_corridor.sh --use_gpu --output_path ~/CuriousNetwork/nn/cnn_autoencoder/2/--name n --type cnn_autoencoder --batch_size 20--data_augmentation --learning_rate 0.001 --epoch_count 20 --weight_decay 0 --cnn_autoencoder_starting_feature_map 2 --cnn_autoencoder_growth_factor 3 --cnn_autoencoder_kernel_size 3
sbatch train_corridor.sh --use_gpu --output_path ~/CuriousNetwork/nn/cnn_autoencoder/4/--name n --type cnn_autoencoder --batch_size 20--data_augmentation --learning_rate 0.001 --epoch_count 20 --weight_decay 0 --cnn_autoencoder_starting_feature_map 4 --cnn_autoencoder_growth_factor 2 --cnn_autoencoder_kernel_size 3
sbatch train_corridor.sh --use_gpu --output_path ~/CuriousNetwork/nn/cnn_autoencoder/4/--name n --type cnn_autoencoder --batch_size 20--data_augmentation --learning_rate 0.001 --epoch_count 20 --weight_decay 0 --cnn_autoencoder_starting_feature_map 4 --cnn_autoencoder_growth_factor 3 --cnn_autoencoder_kernel_size 3
sbatch train_corridor.sh --use_gpu --output_path ~/CuriousNetwork/nn/cnn_autoencoder/8/--name n --type cnn_autoencoder --batch_size 20--data_augmentation --learning_rate 0.001 --epoch_count 20 --weight_decay 0 --cnn_autoencoder_starting_feature_map 8 --cnn_autoencoder_growth_factor 2 --cnn_autoencoder_kernel_size 3
sbatch train_corridor.sh --use_gpu --output_path ~/CuriousNetwork/nn/cnn_autoencoder/8/--name n --type cnn_autoencoder --batch_size 20--data_augmentation --learning_rate 0.001 --epoch_count 20 --weight_decay 0 --cnn_autoencoder_starting_feature_map 8 --cnn_autoencoder_growth_factor 3 --cnn_autoencoder_kernel_size 3
sbatch train_corridor.sh --use_gpu --output_path ~/CuriousNetwork/nn/cnn_vae/start_feature_maps_2/growth_factor_2/--name n --type cnn_vae --batch_size 20 --learning_rate 0.001 --epoch_count 20 --weight_decay 0 --cnn_autoencoder_starting_feature_map 2 --cnn_autoencoder_growth_factor 2 --cnn_autoencoder_kernel_size 3
sbatch train_corridor.sh --use_gpu --output_path ~/CuriousNetwork/nn/cnn_vae/start_feature_maps_2/growth_factor_3/--name n --type cnn_vae --batch_size 20 --learning_rate 0.001 --epoch_count 20 --weight_decay 0 --cnn_autoencoder_starting_feature_map 2 --cnn_autoencoder_growth_factor 3 --cnn_autoencoder_kernel_size 3
sbatch train_corridor.sh --use_gpu --output_path ~/CuriousNetwork/nn/cnn_vae/start_feature_maps_4/growth_factor_2/--name n --type cnn_vae --batch_size 20 --learning_rate 0.001 --epoch_count 20 --weight_decay 0 --cnn_autoencoder_starting_feature_map 4 --cnn_autoencoder_growth_factor 2 --cnn_autoencoder_kernel_size 3
sbatch train_corridor.sh --use_gpu --output_path ~/CuriousNetwork/nn/cnn_vae/start_feature_maps_4/growth_factor_3/--name n --type cnn_vae --batch_size 20 --learning_rate 0.001 --epoch_count 20 --weight_decay 0 --cnn_autoencoder_starting_feature_map 4 --cnn_autoencoder_growth_factor 3 --cnn_autoencoder_kernel_size 3
sbatch train_corridor.sh --use_gpu --output_path ~/CuriousNetwork/nn/cnn_vae/start_feature_maps_8/growth_factor_2/--name n --type cnn_vae --batch_size 20 --learning_rate 0.001 --epoch_count 20 --weight_decay 0 --cnn_autoencoder_starting_feature_map 8 --cnn_autoencoder_growth_factor 2 --cnn_autoencoder_kernel_size 3
sbatch train_corridor.sh --use_gpu --output_path ~/CuriousNetwork/nn/cnn_vae/start_feature_maps_8/growth_factor_3/--name n --type cnn_vae --batch_size 20 --learning_rate 0.001 --epoch_count 20 --weight_decay 0 --cnn_autoencoder_starting_feature_map 8 --cnn_autoencoder_growth_factor 3 --cnn_autoencoder_kernel_size 3
sbatch train_corridor.sh --use_gpu --output_path ~/CuriousNetwork/nn/cnn_vae/start_feature_maps_2/growth_factor_2/--name n --type cnn_vae --batch_size 20--data_augmentation --learning_rate 0.001 --epoch_count 20 --weight_decay 0 --cnn_autoencoder_starting_feature_map 2 --cnn_autoencoder_growth_factor 2 --cnn_autoencoder_kernel_size 3
sbatch train_corridor.sh --use_gpu --output_path ~/CuriousNetwork/nn/cnn_vae/start_feature_maps_2/growth_factor_3/--name n --type cnn_vae --batch_size 20--data_augmentation --learning_rate 0.001 --epoch_count 20 --weight_decay 0 --cnn_autoencoder_starting_feature_map 2 --cnn_autoencoder_growth_factor 3 --cnn_autoencoder_kernel_size 3
sbatch train_corridor.sh --use_gpu --output_path ~/CuriousNetwork/nn/cnn_vae/start_feature_maps_4/growth_factor_2/--name n --type cnn_vae --batch_size 20--data_augmentation --learning_rate 0.001 --epoch_count 20 --weight_decay 0 --cnn_autoencoder_starting_feature_map 4 --cnn_autoencoder_growth_factor 2 --cnn_autoencoder_kernel_size 3
sbatch train_corridor.sh --use_gpu --output_path ~/CuriousNetwork/nn/cnn_vae/start_feature_maps_4/growth_factor_3/--name n --type cnn_vae --batch_size 20--data_augmentation --learning_rate 0.001 --epoch_count 20 --weight_decay 0 --cnn_autoencoder_starting_feature_map 4 --cnn_autoencoder_growth_factor 3 --cnn_autoencoder_kernel_size 3
sbatch train_corridor.sh --use_gpu --output_path ~/CuriousNetwork/nn/cnn_vae/start_feature_maps_8/growth_factor_2/--name n --type cnn_vae --batch_size 20--data_augmentation --learning_rate 0.001 --epoch_count 20 --weight_decay 0 --cnn_autoencoder_starting_feature_map 8 --cnn_autoencoder_growth_factor 2 --cnn_autoencoder_kernel_size 3
sbatch train_corridor.sh --use_gpu --output_path ~/CuriousNetwork/nn/cnn_vae/start_feature_maps_8/growth_factor_3/--name n --type cnn_vae --batch_size 20--data_augmentation --learning_rate 0.001 --epoch_count 20 --weight_decay 0 --cnn_autoencoder_starting_feature_map 8 --cnn_autoencoder_growth_factor 3 --cnn_autoencoder_kernel_size 3
sbatch train_corridor.sh --use_gpu --output_path ~/CuriousNetwork/nn/vgg16_backend_autoencoder/data_augmentation_0/--name n --type vgg16_backend_autoencoder --batch_size 20 --learning_rate 0.001 --epoch_count 20 --weight_decay 0
sbatch train_corridor.sh --use_gpu --output_path ~/CuriousNetwork/nn/vgg16_backend_autoencoder/data_augmentation_0/--name n --type vgg16_backend_autoencoder --batch_size 20 --learning_rate 0.001 --epoch_count 20 --weight_decay 0
sbatch train_corridor.sh --use_gpu --output_path ~/CuriousNetwork/nn/vgg16_backend_autoencoder/data_augmentation_0/--name n --type vgg16_backend_autoencoder --batch_size 20 --learning_rate 0.001 --epoch_count 20 --weight_decay 0
sbatch train_corridor.sh --use_gpu --output_path ~/CuriousNetwork/nn/vgg16_backend_autoencoder/data_augmentation_0/--name n --type vgg16_backend_autoencoder --batch_size 20 --learning_rate 0.001 --epoch_count 20 --weight_decay 0
sbatch train_corridor.sh --use_gpu --output_path ~/CuriousNetwork/nn/vgg16_backend_autoencoder/data_augmentation_0/--name n --type vgg16_backend_autoencoder --batch_size 20 --learning_rate 0.001 --epoch_count 20 --weight_decay 0
sbatch train_corridor.sh --use_gpu --output_path ~/CuriousNetwork/nn/vgg16_backend_autoencoder/data_augmentation_0/--name n --type vgg16_backend_autoencoder --batch_size 20 --learning_rate 0.001 --epoch_count 20 --weight_decay 0
sbatch train_corridor.sh --use_gpu --output_path ~/CuriousNetwork/nn/vgg16_backend_autoencoder/data_augmentation_1/--name n --type vgg16_backend_autoencoder --batch_size 20--data_augmentation --learning_rate 0.001 --epoch_count 20 --weight_decay 0
sbatch train_corridor.sh --use_gpu --output_path ~/CuriousNetwork/nn/vgg16_backend_autoencoder/data_augmentation_1/--name n --type vgg16_backend_autoencoder --batch_size 20--data_augmentation --learning_rate 0.001 --epoch_count 20 --weight_decay 0
sbatch train_corridor.sh --use_gpu --output_path ~/CuriousNetwork/nn/vgg16_backend_autoencoder/data_augmentation_1/--name n --type vgg16_backend_autoencoder --batch_size 20--data_augmentation --learning_rate 0.001 --epoch_count 20 --weight_decay 0
sbatch train_corridor.sh --use_gpu --output_path ~/CuriousNetwork/nn/vgg16_backend_autoencoder/data_augmentation_1/--name n --type vgg16_backend_autoencoder --batch_size 20--data_augmentation --learning_rate 0.001 --epoch_count 20 --weight_decay 0
sbatch train_corridor.sh --use_gpu --output_path ~/CuriousNetwork/nn/vgg16_backend_autoencoder/data_augmentation_1/--name n --type vgg16_backend_autoencoder --batch_size 20--data_augmentation --learning_rate 0.001 --epoch_count 20 --weight_decay 0
sbatch train_corridor.sh --use_gpu --output_path ~/CuriousNetwork/nn/vgg16_backend_autoencoder/data_augmentation_1/--name n --type vgg16_backend_autoencoder --batch_size 20--data_augmentation --learning_rate 0.001 --epoch_count 20 --weight_decay 0
sbatch train_corridor.sh --use_gpu --output_path ~/CuriousNetwork/nn/small_cnn/0.001/first_output_channels_2/growth_rate_2/name n --type small_cnn --batch_size 20 --learning_rate 0.001 --epoch_count 20 --weight_decay 0 --small_cnn_kernel_size 3 --small_cnn_first_output_channels 2 --small_cnn_growth_rate 2
sbatch train_corridor.sh --use_gpu --output_path ~/CuriousNetwork/nn/small_cnn/0.001/first_output_channels_2/growth_rate_3/name n --type small_cnn --batch_size 20 --learning_rate 0.001 --epoch_count 20 --weight_decay 0 --small_cnn_kernel_size 3 --small_cnn_first_output_channels 2 --small_cnn_growth_rate 3
sbatch train_corridor.sh --use_gpu --output_path ~/CuriousNetwork/nn/small_cnn/0.001/first_output_channels_4/growth_rate_2/name n --type small_cnn --batch_size 20 --learning_rate 0.001 --epoch_count 20 --weight_decay 0 --small_cnn_kernel_size 3 --small_cnn_first_output_channels 4 --small_cnn_growth_rate 2
sbatch train_corridor.sh --use_gpu --output_path ~/CuriousNetwork/nn/small_cnn/0.001/first_output_channels_4/growth_rate_3/name n --type small_cnn --batch_size 20 --learning_rate 0.001 --epoch_count 20 --weight_decay 0 --small_cnn_kernel_size 3 --small_cnn_first_output_channels 4 --small_cnn_growth_rate 3
sbatch train_corridor.sh --use_gpu --output_path ~/CuriousNetwork/nn/small_cnn/0.001/first_output_channels_8/growth_rate_2/name n --type small_cnn --batch_size 20 --learning_rate 0.001 --epoch_count 20 --weight_decay 0 --small_cnn_kernel_size 3 --small_cnn_first_output_channels 8 --small_cnn_growth_rate 2
sbatch train_corridor.sh --use_gpu --output_path ~/CuriousNetwork/nn/small_cnn/0.001/first_output_channels_8/growth_rate_3/name n --type small_cnn --batch_size 20 --learning_rate 0.001 --epoch_count 20 --weight_decay 0 --small_cnn_kernel_size 3 --small_cnn_first_output_channels 8 --small_cnn_growth_rate 3
sbatch train_corridor.sh --use_gpu --output_path ~/CuriousNetwork/nn/small_cnn/0.001/first_output_channels_16/growth_rate_2/name n --type small_cnn --batch_size 20 --learning_rate 0.001 --epoch_count 20 --weight_decay 0 --small_cnn_kernel_size 3 --small_cnn_first_output_channels 16 --small_cnn_growth_rate 2
sbatch train_corridor.sh --use_gpu --output_path ~/CuriousNetwork/nn/small_cnn/0.001/first_output_channels_16/growth_rate_3/name n --type small_cnn --batch_size 20 --learning_rate 0.001 --epoch_count 20 --weight_decay 0 --small_cnn_kernel_size 3 --small_cnn_first_output_channels 16 --small_cnn_growth_rate 3
sbatch train_corridor.sh --use_gpu --output_path ~/CuriousNetwork/nn/small_cnn/0.001/first_output_channels_2/growth_rate_2/name n --type small_cnn --batch_size 20--data_augmentation --learning_rate 0.001 --epoch_count 20 --weight_decay 0 --small_cnn_kernel_size 3 --small_cnn_first_output_channels 2 --small_cnn_growth_rate 2
sbatch train_corridor.sh --use_gpu --output_path ~/CuriousNetwork/nn/small_cnn/0.001/first_output_channels_2/growth_rate_3/name n --type small_cnn --batch_size 20--data_augmentation --learning_rate 0.001 --epoch_count 20 --weight_decay 0 --small_cnn_kernel_size 3 --small_cnn_first_output_channels 2 --small_cnn_growth_rate 3
sbatch train_corridor.sh --use_gpu --output_path ~/CuriousNetwork/nn/small_cnn/0.001/first_output_channels_4/growth_rate_2/name n --type small_cnn --batch_size 20--data_augmentation --learning_rate 0.001 --epoch_count 20 --weight_decay 0 --small_cnn_kernel_size 3 --small_cnn_first_output_channels 4 --small_cnn_growth_rate 2
sbatch train_corridor.sh --use_gpu --output_path ~/CuriousNetwork/nn/small_cnn/0.001/first_output_channels_4/growth_rate_3/name n --type small_cnn --batch_size 20--data_augmentation --learning_rate 0.001 --epoch_count 20 --weight_decay 0 --small_cnn_kernel_size 3 --small_cnn_first_output_channels 4 --small_cnn_growth_rate 3
sbatch train_corridor.sh --use_gpu --output_path ~/CuriousNetwork/nn/small_cnn/0.001/first_output_channels_8/growth_rate_2/name n --type small_cnn --batch_size 20--data_augmentation --learning_rate 0.001 --epoch_count 20 --weight_decay 0 --small_cnn_kernel_size 3 --small_cnn_first_output_channels 8 --small_cnn_growth_rate 2
sbatch train_corridor.sh --use_gpu --output_path ~/CuriousNetwork/nn/small_cnn/0.001/first_output_channels_8/growth_rate_3/name n --type small_cnn --batch_size 20--data_augmentation --learning_rate 0.001 --epoch_count 20 --weight_decay 0 --small_cnn_kernel_size 3 --small_cnn_first_output_channels 8 --small_cnn_growth_rate 3
sbatch train_corridor.sh --use_gpu --output_path ~/CuriousNetwork/nn/small_cnn/0.001/first_output_channels_16/growth_rate_2/name n --type small_cnn --batch_size 20--data_augmentation --learning_rate 0.001 --epoch_count 20 --weight_decay 0 --small_cnn_kernel_size 3 --small_cnn_first_output_channels 16 --small_cnn_growth_rate 2
sbatch train_corridor.sh --use_gpu --output_path ~/CuriousNetwork/nn/small_cnn/0.001/first_output_channels_16/growth_rate_3/name n --type small_cnn --batch_size 20--data_augmentation --learning_rate 0.001 --epoch_count 20 --weight_decay 0 --small_cnn_kernel_size 3 --small_cnn_first_output_channels 16 --small_cnn_growth_rate 3

sbatch train_tunnel.sh --use_gpu --output_path ~/CuriousNetwork/nn/cnn_autoencoder/2/--name n --type cnn_autoencoder --batch_size 20 --learning_rate 0.001 --epoch_count 20 --weight_decay 0 --cnn_autoencoder_starting_feature_map 2 --cnn_autoencoder_growth_factor 2 --cnn_autoencoder_kernel_size 3
sbatch train_tunnel.sh --use_gpu --output_path ~/CuriousNetwork/nn/cnn_autoencoder/2/--name n --type cnn_autoencoder --batch_size 20 --learning_rate 0.001 --epoch_count 20 --weight_decay 0 --cnn_autoencoder_starting_feature_map 2 --cnn_autoencoder_growth_factor 3 --cnn_autoencoder_kernel_size 3
sbatch train_tunnel.sh --use_gpu --output_path ~/CuriousNetwork/nn/cnn_autoencoder/4/--name n --type cnn_autoencoder --batch_size 20 --learning_rate 0.001 --epoch_count 20 --weight_decay 0 --cnn_autoencoder_starting_feature_map 4 --cnn_autoencoder_growth_factor 2 --cnn_autoencoder_kernel_size 3
sbatch train_tunnel.sh --use_gpu --output_path ~/CuriousNetwork/nn/cnn_autoencoder/4/--name n --type cnn_autoencoder --batch_size 20 --learning_rate 0.001 --epoch_count 20 --weight_decay 0 --cnn_autoencoder_starting_feature_map 4 --cnn_autoencoder_growth_factor 3 --cnn_autoencoder_kernel_size 3
sbatch train_tunnel.sh --use_gpu --output_path ~/CuriousNetwork/nn/cnn_autoencoder/8/--name n --type cnn_autoencoder --batch_size 20 --learning_rate 0.001 --epoch_count 20 --weight_decay 0 --cnn_autoencoder_starting_feature_map 8 --cnn_autoencoder_growth_factor 2 --cnn_autoencoder_kernel_size 3
sbatch train_tunnel.sh --use_gpu --output_path ~/CuriousNetwork/nn/cnn_autoencoder/8/--name n --type cnn_autoencoder --batch_size 20 --learning_rate 0.001 --epoch_count 20 --weight_decay 0 --cnn_autoencoder_starting_feature_map 8 --cnn_autoencoder_growth_factor 3 --cnn_autoencoder_kernel_size 3
sbatch train_tunnel.sh --use_gpu --output_path ~/CuriousNetwork/nn/cnn_autoencoder/2/--name n --type cnn_autoencoder --batch_size 20--data_augmentation --learning_rate 0.001 --epoch_count 20 --weight_decay 0 --cnn_autoencoder_starting_feature_map 2 --cnn_autoencoder_growth_factor 2 --cnn_autoencoder_kernel_size 3
sbatch train_tunnel.sh --use_gpu --output_path ~/CuriousNetwork/nn/cnn_autoencoder/2/--name n --type cnn_autoencoder --batch_size 20--data_augmentation --learning_rate 0.001 --epoch_count 20 --weight_decay 0 --cnn_autoencoder_starting_feature_map 2 --cnn_autoencoder_growth_factor 3 --cnn_autoencoder_kernel_size 3
sbatch train_tunnel.sh --use_gpu --output_path ~/CuriousNetwork/nn/cnn_autoencoder/4/--name n --type cnn_autoencoder --batch_size 20--data_augmentation --learning_rate 0.001 --epoch_count 20 --weight_decay 0 --cnn_autoencoder_starting_feature_map 4 --cnn_autoencoder_growth_factor 2 --cnn_autoencoder_kernel_size 3
sbatch train_tunnel.sh --use_gpu --output_path ~/CuriousNetwork/nn/cnn_autoencoder/4/--name n --type cnn_autoencoder --batch_size 20--data_augmentation --learning_rate 0.001 --epoch_count 20 --weight_decay 0 --cnn_autoencoder_starting_feature_map 4 --cnn_autoencoder_growth_factor 3 --cnn_autoencoder_kernel_size 3
sbatch train_tunnel.sh --use_gpu --output_path ~/CuriousNetwork/nn/cnn_autoencoder/8/--name n --type cnn_autoencoder --batch_size 20--data_augmentation --learning_rate 0.001 --epoch_count 20 --weight_decay 0 --cnn_autoencoder_starting_feature_map 8 --cnn_autoencoder_growth_factor 2 --cnn_autoencoder_kernel_size 3
sbatch train_tunnel.sh --use_gpu --output_path ~/CuriousNetwork/nn/cnn_autoencoder/8/--name n --type cnn_autoencoder --batch_size 20--data_augmentation --learning_rate 0.001 --epoch_count 20 --weight_decay 0 --cnn_autoencoder_starting_feature_map 8 --cnn_autoencoder_growth_factor 3 --cnn_autoencoder_kernel_size 3
sbatch train_tunnel.sh --use_gpu --output_path ~/CuriousNetwork/nn/cnn_vae/start_feature_maps_2/growth_factor_2/--name n --type cnn_vae --batch_size 20 --learning_rate 0.001 --epoch_count 20 --weight_decay 0 --cnn_autoencoder_starting_feature_map 2 --cnn_autoencoder_growth_factor 2 --cnn_autoencoder_kernel_size 3
sbatch train_tunnel.sh --use_gpu --output_path ~/CuriousNetwork/nn/cnn_vae/start_feature_maps_2/growth_factor_3/--name n --type cnn_vae --batch_size 20 --learning_rate 0.001 --epoch_count 20 --weight_decay 0 --cnn_autoencoder_starting_feature_map 2 --cnn_autoencoder_growth_factor 3 --cnn_autoencoder_kernel_size 3
sbatch train_tunnel.sh --use_gpu --output_path ~/CuriousNetwork/nn/cnn_vae/start_feature_maps_4/growth_factor_2/--name n --type cnn_vae --batch_size 20 --learning_rate 0.001 --epoch_count 20 --weight_decay 0 --cnn_autoencoder_starting_feature_map 4 --cnn_autoencoder_growth_factor 2 --cnn_autoencoder_kernel_size 3
sbatch train_tunnel.sh --use_gpu --output_path ~/CuriousNetwork/nn/cnn_vae/start_feature_maps_4/growth_factor_3/--name n --type cnn_vae --batch_size 20 --learning_rate 0.001 --epoch_count 20 --weight_decay 0 --cnn_autoencoder_starting_feature_map 4 --cnn_autoencoder_growth_factor 3 --cnn_autoencoder_kernel_size 3
sbatch train_tunnel.sh --use_gpu --output_path ~/CuriousNetwork/nn/cnn_vae/start_feature_maps_8/growth_factor_2/--name n --type cnn_vae --batch_size 20 --learning_rate 0.001 --epoch_count 20 --weight_decay 0 --cnn_autoencoder_starting_feature_map 8 --cnn_autoencoder_growth_factor 2 --cnn_autoencoder_kernel_size 3
sbatch train_tunnel.sh --use_gpu --output_path ~/CuriousNetwork/nn/cnn_vae/start_feature_maps_8/growth_factor_3/--name n --type cnn_vae --batch_size 20 --learning_rate 0.001 --epoch_count 20 --weight_decay 0 --cnn_autoencoder_starting_feature_map 8 --cnn_autoencoder_growth_factor 3 --cnn_autoencoder_kernel_size 3
sbatch train_tunnel.sh --use_gpu --output_path ~/CuriousNetwork/nn/cnn_vae/start_feature_maps_2/growth_factor_2/--name n --type cnn_vae --batch_size 20--data_augmentation --learning_rate 0.001 --epoch_count 20 --weight_decay 0 --cnn_autoencoder_starting_feature_map 2 --cnn_autoencoder_growth_factor 2 --cnn_autoencoder_kernel_size 3
sbatch train_tunnel.sh --use_gpu --output_path ~/CuriousNetwork/nn/cnn_vae/start_feature_maps_2/growth_factor_3/--name n --type cnn_vae --batch_size 20--data_augmentation --learning_rate 0.001 --epoch_count 20 --weight_decay 0 --cnn_autoencoder_starting_feature_map 2 --cnn_autoencoder_growth_factor 3 --cnn_autoencoder_kernel_size 3
sbatch train_tunnel.sh --use_gpu --output_path ~/CuriousNetwork/nn/cnn_vae/start_feature_maps_4/growth_factor_2/--name n --type cnn_vae --batch_size 20--data_augmentation --learning_rate 0.001 --epoch_count 20 --weight_decay 0 --cnn_autoencoder_starting_feature_map 4 --cnn_autoencoder_growth_factor 2 --cnn_autoencoder_kernel_size 3
sbatch train_tunnel.sh --use_gpu --output_path ~/CuriousNetwork/nn/cnn_vae/start_feature_maps_4/growth_factor_3/--name n --type cnn_vae --batch_size 20--data_augmentation --learning_rate 0.001 --epoch_count 20 --weight_decay 0 --cnn_autoencoder_starting_feature_map 4 --cnn_autoencoder_growth_factor 3 --cnn_autoencoder_kernel_size 3
sbatch train_tunnel.sh --use_gpu --output_path ~/CuriousNetwork/nn/cnn_vae/start_feature_maps_8/growth_factor_2/--name n --type cnn_vae --batch_size 20--data_augmentation --learning_rate 0.001 --epoch_count 20 --weight_decay 0 --cnn_autoencoder_starting_feature_map 8 --cnn_autoencoder_growth_factor 2 --cnn_autoencoder_kernel_size 3
sbatch train_tunnel.sh --use_gpu --output_path ~/CuriousNetwork/nn/cnn_vae/start_feature_maps_8/growth_factor_3/--name n --type cnn_vae --batch_size 20--data_augmentation --learning_rate 0.001 --epoch_count 20 --weight_decay 0 --cnn_autoencoder_starting_feature_map 8 --cnn_autoencoder_growth_factor 3 --cnn_autoencoder_kernel_size 3
sbatch train_tunnel.sh --use_gpu --output_path ~/CuriousNetwork/nn/vgg16_backend_autoencoder/data_augmentation_0/--name n --type vgg16_backend_autoencoder --batch_size 20 --learning_rate 0.001 --epoch_count 20 --weight_decay 0
sbatch train_tunnel.sh --use_gpu --output_path ~/CuriousNetwork/nn/vgg16_backend_autoencoder/data_augmentation_0/--name n --type vgg16_backend_autoencoder --batch_size 20 --learning_rate 0.001 --epoch_count 20 --weight_decay 0
sbatch train_tunnel.sh --use_gpu --output_path ~/CuriousNetwork/nn/vgg16_backend_autoencoder/data_augmentation_0/--name n --type vgg16_backend_autoencoder --batch_size 20 --learning_rate 0.001 --epoch_count 20 --weight_decay 0
sbatch train_tunnel.sh --use_gpu --output_path ~/CuriousNetwork/nn/vgg16_backend_autoencoder/data_augmentation_0/--name n --type vgg16_backend_autoencoder --batch_size 20 --learning_rate 0.001 --epoch_count 20 --weight_decay 0
sbatch train_tunnel.sh --use_gpu --output_path ~/CuriousNetwork/nn/vgg16_backend_autoencoder/data_augmentation_0/--name n --type vgg16_backend_autoencoder --batch_size 20 --learning_rate 0.001 --epoch_count 20 --weight_decay 0
sbatch train_tunnel.sh --use_gpu --output_path ~/CuriousNetwork/nn/vgg16_backend_autoencoder/data_augmentation_0/--name n --type vgg16_backend_autoencoder --batch_size 20 --learning_rate 0.001 --epoch_count 20 --weight_decay 0
sbatch train_tunnel.sh --use_gpu --output_path ~/CuriousNetwork/nn/vgg16_backend_autoencoder/data_augmentation_1/--name n --type vgg16_backend_autoencoder --batch_size 20--data_augmentation --learning_rate 0.001 --epoch_count 20 --weight_decay 0
sbatch train_tunnel.sh --use_gpu --output_path ~/CuriousNetwork/nn/vgg16_backend_autoencoder/data_augmentation_1/--name n --type vgg16_backend_autoencoder --batch_size 20--data_augmentation --learning_rate 0.001 --epoch_count 20 --weight_decay 0
sbatch train_tunnel.sh --use_gpu --output_path ~/CuriousNetwork/nn/vgg16_backend_autoencoder/data_augmentation_1/--name n --type vgg16_backend_autoencoder --batch_size 20--data_augmentation --learning_rate 0.001 --epoch_count 20 --weight_decay 0
sbatch train_tunnel.sh --use_gpu --output_path ~/CuriousNetwork/nn/vgg16_backend_autoencoder/data_augmentation_1/--name n --type vgg16_backend_autoencoder --batch_size 20--data_augmentation --learning_rate 0.001 --epoch_count 20 --weight_decay 0
sbatch train_tunnel.sh --use_gpu --output_path ~/CuriousNetwork/nn/vgg16_backend_autoencoder/data_augmentation_1/--name n --type vgg16_backend_autoencoder --batch_size 20--data_augmentation --learning_rate 0.001 --epoch_count 20 --weight_decay 0
sbatch train_tunnel.sh --use_gpu --output_path ~/CuriousNetwork/nn/vgg16_backend_autoencoder/data_augmentation_1/--name n --type vgg16_backend_autoencoder --batch_size 20--data_augmentation --learning_rate 0.001 --epoch_count 20 --weight_decay 0
sbatch train_tunnel.sh --use_gpu --output_path ~/CuriousNetwork/nn/small_cnn/0.001/first_output_channels_2/growth_rate_2/name n --type small_cnn --batch_size 20 --learning_rate 0.001 --epoch_count 20 --weight_decay 0 --small_cnn_kernel_size 3 --small_cnn_first_output_channels 2 --small_cnn_growth_rate 2
sbatch train_tunnel.sh --use_gpu --output_path ~/CuriousNetwork/nn/small_cnn/0.001/first_output_channels_2/growth_rate_3/name n --type small_cnn --batch_size 20 --learning_rate 0.001 --epoch_count 20 --weight_decay 0 --small_cnn_kernel_size 3 --small_cnn_first_output_channels 2 --small_cnn_growth_rate 3
sbatch train_tunnel.sh --use_gpu --output_path ~/CuriousNetwork/nn/small_cnn/0.001/first_output_channels_4/growth_rate_2/name n --type small_cnn --batch_size 20 --learning_rate 0.001 --epoch_count 20 --weight_decay 0 --small_cnn_kernel_size 3 --small_cnn_first_output_channels 4 --small_cnn_growth_rate 2
sbatch train_tunnel.sh --use_gpu --output_path ~/CuriousNetwork/nn/small_cnn/0.001/first_output_channels_4/growth_rate_3/name n --type small_cnn --batch_size 20 --learning_rate 0.001 --epoch_count 20 --weight_decay 0 --small_cnn_kernel_size 3 --small_cnn_first_output_channels 4 --small_cnn_growth_rate 3
sbatch train_tunnel.sh --use_gpu --output_path ~/CuriousNetwork/nn/small_cnn/0.001/first_output_channels_8/growth_rate_2/name n --type small_cnn --batch_size 20 --learning_rate 0.001 --epoch_count 20 --weight_decay 0 --small_cnn_kernel_size 3 --small_cnn_first_output_channels 8 --small_cnn_growth_rate 2
sbatch train_tunnel.sh --use_gpu --output_path ~/CuriousNetwork/nn/small_cnn/0.001/first_output_channels_8/growth_rate_3/name n --type small_cnn --batch_size 20 --learning_rate 0.001 --epoch_count 20 --weight_decay 0 --small_cnn_kernel_size 3 --small_cnn_first_output_channels 8 --small_cnn_growth_rate 3
sbatch train_tunnel.sh --use_gpu --output_path ~/CuriousNetwork/nn/small_cnn/0.001/first_output_channels_16/growth_rate_2/name n --type small_cnn --batch_size 20 --learning_rate 0.001 --epoch_count 20 --weight_decay 0 --small_cnn_kernel_size 3 --small_cnn_first_output_channels 16 --small_cnn_growth_rate 2
sbatch train_tunnel.sh --use_gpu --output_path ~/CuriousNetwork/nn/small_cnn/0.001/first_output_channels_16/growth_rate_3/name n --type small_cnn --batch_size 20 --learning_rate 0.001 --epoch_count 20 --weight_decay 0 --small_cnn_kernel_size 3 --small_cnn_first_output_channels 16 --small_cnn_growth_rate 3
sbatch train_tunnel.sh --use_gpu --output_path ~/CuriousNetwork/nn/small_cnn/0.001/first_output_channels_2/growth_rate_2/name n --type small_cnn --batch_size 20--data_augmentation --learning_rate 0.001 --epoch_count 20 --weight_decay 0 --small_cnn_kernel_size 3 --small_cnn_first_output_channels 2 --small_cnn_growth_rate 2
sbatch train_tunnel.sh --use_gpu --output_path ~/CuriousNetwork/nn/small_cnn/0.001/first_output_channels_2/growth_rate_3/name n --type small_cnn --batch_size 20--data_augmentation --learning_rate 0.001 --epoch_count 20 --weight_decay 0 --small_cnn_kernel_size 3 --small_cnn_first_output_channels 2 --small_cnn_growth_rate 3
sbatch train_tunnel.sh --use_gpu --output_path ~/CuriousNetwork/nn/small_cnn/0.001/first_output_channels_4/growth_rate_2/name n --type small_cnn --batch_size 20--data_augmentation --learning_rate 0.001 --epoch_count 20 --weight_decay 0 --small_cnn_kernel_size 3 --small_cnn_first_output_channels 4 --small_cnn_growth_rate 2
sbatch train_tunnel.sh --use_gpu --output_path ~/CuriousNetwork/nn/small_cnn/0.001/first_output_channels_4/growth_rate_3/name n --type small_cnn --batch_size 20--data_augmentation --learning_rate 0.001 --epoch_count 20 --weight_decay 0 --small_cnn_kernel_size 3 --small_cnn_first_output_channels 4 --small_cnn_growth_rate 3
sbatch train_tunnel.sh --use_gpu --output_path ~/CuriousNetwork/nn/small_cnn/0.001/first_output_channels_8/growth_rate_2/name n --type small_cnn --batch_size 20--data_augmentation --learning_rate 0.001 --epoch_count 20 --weight_decay 0 --small_cnn_kernel_size 3 --small_cnn_first_output_channels 8 --small_cnn_growth_rate 2
sbatch train_tunnel.sh --use_gpu --output_path ~/CuriousNetwork/nn/small_cnn/0.001/first_output_channels_8/growth_rate_3/name n --type small_cnn --batch_size 20--data_augmentation --learning_rate 0.001 --epoch_count 20 --weight_decay 0 --small_cnn_kernel_size 3 --small_cnn_first_output_channels 8 --small_cnn_growth_rate 3
sbatch train_tunnel.sh --use_gpu --output_path ~/CuriousNetwork/nn/small_cnn/0.001/first_output_channels_16/growth_rate_2/name n --type small_cnn --batch_size 20--data_augmentation --learning_rate 0.001 --epoch_count 20 --weight_decay 0 --small_cnn_kernel_size 3 --small_cnn_first_output_channels 16 --small_cnn_growth_rate 2
sbatch train_tunnel.sh --use_gpu --output_path ~/CuriousNetwork/nn/small_cnn/0.001/first_output_channels_16/growth_rate_3/name n --type small_cnn --batch_size 20--data_augmentation --learning_rate 0.001 --epoch_count 20 --weight_decay 0 --small_cnn_kernel_size 3 --small_cnn_first_output_channels 16 --small_cnn_growth_rate 3
